### ISSUE TITLE
Problem with PRPT

### ISSUE THREAD

**Issue by jagnaldo** [Mgiepz/saiku-adhoc#130] opened 2012-03-20 15:12 UTC
Hi, when i export PRPT and execute the file, there´s a message error: 'Could not fetch parameters'.

The screen's and log´s are bellow:

http://dug.im/4ce60
http://dug.im/4a3fc
http://dug.im/f6f0d

thanks.

Agnaldo

**Comment by Mgiepz** [comment] 2012-03-20 16:02
I can reproduce that. Since I fundamentally changed some things regarding the query mechanism to fixe the user/password and temp-dir configuration, I have to get some input before i can fix this.

**Comment by jagnaldo** [comment] 2012-03-20 17:35
OK. I tested with another file and get other error:

http://dug.im/ba411
http://dug.im/de69a
http://derp.co.uk/519d0

**Comment by Mgiepz** [comment] 2012-03-21 00:50
yes, that is what i expected. it basically says that your reportviewer cant call the cda datasource because it doesnt know the user credentials. Saiku Reporting now has another way of accessing the cda datasource. This other way won't be working in the pentaho reportviewer before biserver version 4.5. 
We are trying to figure out a solution for that

**Comment by jagnaldo** [comment] 2012-03-22 17:09
Hi Mgiepz, only to confirm, ive to wait new instructions isnt it ?

thanks

2012/3/21 Mgiepz <
reply@reply.github.com

**Comment by Mgiepz** [comment] 2012-03-23 13:07
yes. i have a solution where you can optionally enter user/password on prpt export (for biserver 3.10). That solution will use the direct cda-call if it is available and the cda via http as a fallback. I will check that in with a lot of other fixes asap

**Comment by Mgiepz** [comment] 2012-03-27 15:33
checked in. please reinstall everything using ctools-installer, copy over the cda-datasource to web-inf/lib and test

**Comment by jagnaldo** [comment] 2012-04-02 12:37
Hi Mgiepz, sorry for the time response but i was full at work... I downloaded from dev and when i typed file, user and password nothing happens, 

The screen's and log´s are bellow:

http://derp.co.uk/b706c
http://derp.co.uk/69c3d
http://derp.co.uk/6776b

**Comment by Mgiepz** [comment] 2012-04-12 19:27
@jagnaldo: what is the status here? sometime ago it turned out that we included a wrong dependency of the cda-extension. Someone else reported your issue and it seems like updating again to the latest version solved it. can you check and confirm?

**Comment by jagnaldo** [comment] 2012-04-16 20:26
Hi Mgiepz, i installed from dev branch and works fine ! I used user and password joe/password, it is temporary isn´t it ?
thanks.

http://derp.co.uk/78b51

**Comment by Mgiepz** [comment] 2012-04-17 09:03
It will be necessary until pentaho allows local cda-calls in the bi-server, which will be with the next bi-server release. for 3.10 wo can't really work around it, as the opening of our generated prpt's in the reportviewer is "outside of the plugin's domain"

**Closed as completed by Mgiepz** 2012-04-17 09:03 UTC

**Comment by radabada** [comment] 2013-11-08 05:49
Hi, when exporting ad-hoc report made to PRPT file it propmts for username and password, it then saves credentials to prpt. I would appreciate to let saiku store jndi datasource and no user credentials. Is there any configuration to reach this? Or do I have to rewrite a library pentaho-reporting-engine-classic-extensions-cda-xxx.jar used to make export to PRPT working?
Thank you
Radek
